sudo: required
services:
  - docker
before -install:
  - docker build -t ishimosi/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run ishimosi/react-test npm test -- --coverage
after_sucess:
  - docker build -t ishimosi/multi-client ./client
  - docker build -t ishimosi/multi-nginx ./nginx
  - docker build -t ishimosi/multi-server ./server
  - docker build -t ishimosi/multi-worker ./worker
  # log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push them to docker hub
  - docker push ishimosi/multi-client
  - docker push ishimosi/multi-nginx
  - docker push ishimosi/multi-server
  - docker push ishimosi/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-northeast-1-176744623745
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY



